steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-west2-docker.pkg.dev/safety-net-398016/quickstart-docker-repo/quickstart-image:tag1', '.' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'cloudrunservice'
      - '--image'
      - 'us-docker.pkg.dev/cloudrun/container/hello'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-west2-docker.pkg.dev/safety-net-398016/quickstart-docker-repo/quickstart-image:tag1'
