version: '3.9'
name: safetynet

services:
  
  # PostgreSQL database
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sndb
      POSTGRES_USER: snuser
      POSTGRES_PASSWORD: snpassword

  web:
    image: my-django-app-image
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_NAME: mydb
      DJANGO_DB_USER: myuser
      DJANGO_DB_PASSWORD: mypassword

volumes:
  postgres_data
